/**:
  controller_manager:
    ros__parameters:
      update_rate: 500

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
      imu_sensor_broadcaster:
        type: imu_sensor_broadcaster/IMUSensorBroadcaster
      effort_controller:
        type: effort_controllers/JointGroupEffortController
        
  imu_sensor_broadcaster:
    ros__parameters:
      update_rate: 500
      sensor_name: imu
      frame_id:  imu

  joint_state_broadcaster:
    ros__parameters:
      update_rate: 500  # Hz

  effort_controller:
    ros__parameters:
      joints:
          - joint_left_hip
          - joint_left_thigh
          - joint_left_calf
          - joint_left_wheel
          - joint_right_hip
          - joint_right_thigh
          - joint_right_calf
          - joint_right_wheel

