tita_isaacgym:
  model_name: "model_cpu.pt"
  framework: "isaacgym"
  rows: 4
  cols: 3
  dt: 0.0025
  decimation: 4
  num_observations: 33
  observations: ["ang_vel", "gravity_vec", "commands", "dof_pos", "dof_vel", "actions"]
  observations_history: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
#   observations_history: []
  clip_obs: 100.0
  clip_actions_lower: [-100, -100, -100, -100,
                       -100, -100, -100, -100]
  clip_actions_upper: [100, 100, 100, 100,
                       100, 100, 100, 100]
  rl_kp: [40, 40, 40, 40,
          40, 40, 40, 40]
  rl_kd: [1.0, 1.0, 1.0, 1.0,
          1.0, 1.0, 1.0, 1.0]
  # rl_kd: [0.5, 0.5, 0.5, 0.5,
  #         0.5, 0.5, 0.5, 0.5]
  fixed_kp: [80, 80, 80,
             80, 80, 80,
             80, 80, 80,
             80, 80, 80]
  fixed_kd: [3, 3, 3,
             3, 3, 3,
             3, 3, 3,
             3, 3, 3]
  hip_scale_reduction: 0.5
  hip_scale_reduction_indices: [0, 4]
  num_of_dofs: 8
  action_scale: 0.5
  action_pos_scale: 0.25
  action_vel_scale: 0.5
  lin_vel_scale: 2.0
  ang_vel_scale: 0.25
  dof_pos_scale: 1.0
  dof_vel_scale: 0.05
  commands_scale: [2.0, 2.0, 0.25]
  torque_limits: [60.0, 60.0, 60.0, 15.0,
                  60.0, 60.0, 60.0, 15.0]
  default_dof_pos: [ 0.000, 0.8, -1.5, 0.000,
                     0.000, 0.8, -1.5, 0.000]
  joint_controller_names: ["joint_left_hip_controller", "joint_left_thigh_controller", "joint_left_calf_controller", "joint_left_wheel_controller",
                           "joint_right_hip_controller", "joint_right_thigh_controller", "joint_right_calf_controller","joint_right_wheel_controller"]
